spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ncov_m?serverTimezone=GMT%2b8
    username: root
    password: 1347477532
server:
  port: 8081
